### ISSUE TITLE
Integration to OWIN pipeline with Microsoft.Owin.StaticFiles 

### ISSUE THREAD

**Issue by Thorium** [Thorium/Owin.Compression#1]
Currently this module is serving static files from the file system. Instead it could use just compress HTTP-response, so that it could be plugged with other modules, e.g. Microsoft.Owin.StaticFiles NuGet package to do the actual file loading.

The problem seems to be that Microsoft.Owin.StaticFiles won't actually integrate to OWIN-pipeline but it will send the file directly. So there might not be a way to interrupt the HTTP-response. There are very few events (`Microsoft.Owin.StaticFiles.FileServerOptions().StaticFileOptions.OnPrepareResponse`) and it seems that those can't also be to interrupt the actual response.

**Comment by ghost** [comment]
Hi,

i already implemented a Owin Comnpression using Http-Buffer so it intercepts all requests and responses and handles them. it works with static-files too as im only serving my files through owin.staticfiles in my project

Hope it can help you with your project

**Comment by Thorium** [comment]
Thanks!
Fixed.
