### ISSUE TITLE
If the request is being forwarded from one cluster to another. The compression fails probably because it is not checking if response is already compressed

### ISSUE THREAD

**Issue by indiyoapp** [Thorium/Owin.Compression#10]
I was using this library for compression of a response which is for a stateful request. We have a project scenario in our app such that if the project is already open in a cluster(we have multiple clusters in different regions like - East US , South east asia etc) the request gets forwarded to that cluster. What happened was if you just hit one cluster compression was working fine but when the request was being forwarded and as the library is part of middle ware , the library is trying to compress the already compressed response. Library should check if the response is already compressed it should do nothing and just return. It could use response header to add a simple check in usecompress function.

**Comment by Thorium** [comment]
Hi, this is a good idea.
Would you like to make a PR or should I look into this?

**Comment by nirav91** [comment]
I am also facing the similar issue.
Raised a PR to fix this - #11

**Comment by nirav91** [comment]
@Thorium : can you please review the PR?
