### ISSUE TITLE
Inconsistency between .NET Framework version and NuGet package framework versions

### ISSUE THREAD

**Issue by SylwesterZarebski** [Thorium/Owin.Compression#14]
NuGet package is defined as 4.7.2, but from version 1.0.41 library is compiled as 4.8 and can not be used in projects compiled as 4.7.2.
Last compilable with 4.7.2 version is 1.0.40.

Solution: in `paket.template` dependency should be changed to `net48`.

**Comment by Thorium** [comment]
Thanks for reporting. Do you need net 4.7.2 or should I just fix the dependency to be net48 ?

**Comment by SylwesterZarebski** [comment]
Dependency is fine for me, thanks. I'm reporting this just for consistency.
