### ISSUE TITLE
Compression Based on Mime Type of Response

### ISSUE THREAD

**Issue by phil000** [Thorium/Owin.Compression#4]
Hello,
I notice that you may be assuming that anything without an extension is inherently compressable. This is not the case for us, virtually nothing has an extension.
e.g.
GET /swagger/ui/images/logo_small-png

We would really like to be able to define what responses are compressed based on the response mime-type.
At the moment everything and anything without an extension is compressed.

---

 let compressableExtension = 
                        match context.Request.Path.ToString() with
                        | null -> true
                        | x when x.Contains(".") -> 
                            let typemap = settings.AllowedExtensionAndMimeTypes |> Map.ofSeq
                            typemap.ContainsKey(x.Substring(x.LastIndexOf "."))
                        | _ -> true

**Comment by Thorium** [comment]
Thanks, I like this idea. Currently the assumption was that http://asdf/ is request to http://asdf/index.html or similar resource, but you are correct.

**Comment by Thorium** [comment]
Mime type is set to response stream of Owin pipeline.
This  is kind of problem: usually the streams are compressed on-the-fly as-it-comes, but if next owin pipeline module haven't been called yet, MIME-type is not available.

What this means in practice is that compression has to wait the end of OWIN pipeline process before it can get the response and start encoding. I don't know if this can be a problem if your response size is huge or never-ending.

**Comment by Thorium** [comment]
Done in NuGet version 1.0.11.
