### ISSUE TITLE
Is there is any reasons why this package not working with Microsoft.Owin 3.1.0

### ISSUE THREAD

**Issue by alfeg** [Thorium/Owin.Compression#6]
I can see in Nuget descriptions that there is following limitations on dependencies
```
Microsoft.Owin (>= 3.0.1 && < 3.1.0)
```

Is there is any hard reasons on why 3.1.0 owin package is not supported?

**Comment by Thorium** [comment]
No, I think it was earlier version of Paket which wanted to keep manual control over major releases.

Anyways, there is now version Owin.Compression 1.0.15 which is totally the same logics, but reference components updated, so support for Microsoft.Owin 3.1.
