### ISSUE TITLE
ETAG is always the same

### ISSUE THREAD

**Issue by Moachi** [Thorium/Owin.Compression#8]
I have a simple OWIN application. On GET it returns a big chunk of JSON.

When compression enabled, it computes an ETAG and the ETAG remains the same even if the data changes.

After playing a bit with sources it turns out if I change the following line
```fsharp

                    if usecompress && checkNoValidETag(context.Response.Body) then

```
to
```fsharp
                    if usecompress && checkNoValidETag(buffer) then
```
and add this
```fsharp
        let getMd5Hash (item:Stream) =
            item.Position <- 0L
```

it starts to work and properly computes ETAG. 

But it doesn't feel like it's  a correct fix.

**Comment by Thorium** [comment]
The original idea is simply that if the server calculated value over the content ("body") is the same than client already has in ETAG, we don't need to compress and send the resource over the wire.

**Comment by Thorium** [comment]
Hmm... Was the context.Response.Body empty at the time of calculation?

**Comment by Moachi** [comment]
Hi,

after some tests, it turned out that the response buffer has the position pointing to the buffer end thus hashing always returns the same results.

So, this part matters
```fsharp
        let getMd5Hash (item:Stream) =
            item.Position <- 0L
```

With regards to context.Response.Body - it seems unrelated somehow and probably something to deal with many other middlewares I have. 

There is one remark though, you make context.Respones.Body pointing to your buffer and don't restore it before exit. The middleware which executes on top that will try to access context.Response.Body after Next.Invoke might use the incorrect buffer. Not sure if that's a valid concern though.

**Comment by Thorium** [comment]
I have not experienced this. So maybe the order of middleware-registration is significant.

**Comment by Moachi** [comment]
All right,

but what's with regard to the stream position. Will you make the update to change the position into the beginning of the stream during the MD5 hash calculation?

**Comment by Thorium** [comment]
Can you send a PR?

**Comment by Thorium** [comment]
Is this only for streams?

**Comment by Moachi** [comment]
Yeah, it's for streams. That's our use case. I'm not a F# developer, so I might be doing this the wrong way :) 
You might want to check if it's allowed to perform seek operations on the stream. And to position the stream the same way you do in the code below.

**Comment by Thorium** [comment]
Should we reset the position back to original,
e.g.

```fsharp
let getMd5Hash (item:Stream) =
    let hasPos = 
        if item.CanSeek && item.Position > 0L then
            let tmp = item.Position
            item.Position <- 0L
            Some tmp
        else None
    use md5 = System.Security.Cryptography.MD5.Create()
    let res = BitConverter.ToString(md5.ComputeHash(item)).Replace("-","")
    match hasPos with
    | Some x when item.CanSeek -> item.Position <- x
    | _ -> ()
    res
```

**Comment by Moachi** [comment]
I didn't find any info about whether the middleware must persist the state of the Context.Response.Body stream. So I would assume this is not a requirement, however, it won't harm either :)

**Comment by Thorium** [comment]
This is now added to NuGet version 1.1.18. Hopefully helps.

**Comment by Thorium** [comment]
This is now added to NuGet version 1.1.18. Hopefully helps.

**Comment by Moachi** [comment]
It works well. Thank you!
